### ISSUE TITLE
Does this work with Moon Modules 

### ISSUE THREAD

**Issue by 1liminal1** [ajotanc/PixelMagicTool#4]
I'm trying to send a gif to my Moon Modules version of WLED and I get an error telling me the JSON ending is unexpected. 

Have I don't something to my presets and need to re-format the ESP32. Or is this something known with MM?

Thanks :)

**Comment by 1liminal1** [comment]
Is this dead?

**Comment by dosipod** [comment]
@1liminal1 Not sure of your setup size to try and replicate but does it work  with AC .
In all cases using that tool for gif might not the best and it was reported to cause issues ( could be matrix size limitations ) but not enough info provided , works okay for pics   , meanwhile  other tools you might want to look for gifs which I tested and they are much better  :

1) Gif branch https://github.com/Aircoookie/WLED/tree/gif   , the bins are here if you cant compile from source https://github.com/dosipod/WLED_gif_update/actions/runs/10116313741 , as I re-based that on 15 
2) Usermod (client and server ) https://github.com/hughc/wled-pixelart-client

**Comment by 1liminal1** [comment]
Sorry, I should give more context :) 

Its a 64x64 Hub75 Matrix, all the MM 2d effects are working ok and I the base [WLED-PixelArtConverter](https://github.com/werkstrom/WLED-PixelArtConverter) works fine as well. But I'm wanting to do GIFS as playlists. 

Not sure what AC is?

Do these bins have the HUB75 support build in?

Thanks!

**Comment by 1liminal1** [comment]
I actually worked out a way to do it. Separate the gif into frames them upload them as individual presets. 

But I forgot how fickle WLED presets can be when they don't want to work :( :( :(  Im trying to reflash but the old presets seem to be there :(

Anyway, thanks

**Comment by dosipod** [comment]
Yeah might be the size is the issue , and no the hub75 is only supported on MM for now , there is a PR pending in AC ( Aircoookie) .https://github.com/Aircoookie/WLED  
I do also have HUB75 64x64 and might try to do gif and the easy way ( could be the more stable way ) is to add  the usermod to MM . Using presets for gif is not practical  for me nor i think that would be stable but if that works for you then why not 

I would love for the gif branch to be added in MM as that could be the best way for standalone unit  but this is the wrong place to discuss that as might be better in here  https://github.com/MoonModules/WLED/issues

**Comment by softhack007** [comment]
> Does this work with Moon Modules

Latest news: since today, **it does work with MoonModules WLED** --> https://github.com/MoonModules/WLED/issues/172#issuecomment-2441560888

(actually there was just a small patch needed for our development `mdev` version; in the last release it should also work).

Edit: I've actually tested with [PixelArtConverter](https://github.com/werkstrom/WLED-PixelArtConverter/), but the API is the same so i'm confident "if it works in AC WLED, it will also work with MoonModules WLED".

**Comment by 1liminal1** [comment]
> Edit: I've actually tested with [PixelArtConverter](https://github.com/werkstrom/WLED-PixelArtConverter/), but the API is the same so i'm confident "if it works in AC WLED, it will also work with MoonModules WLED".

Is this S3 only, or does it also apply to the ESP32 classic?

Thanks! :)

**Comment by softhack007** [comment]
> Is this S3 only, or does it also apply to the ESP32 classic?

@1liminal1 I've tested the bugfix on -S3 with PSRAM. If you don't need large resolution ("large" = 64x64 HUB75) then it should also work for classic esp32.

The overall tech - storing a sequence of images in presets and making a playlist - is really not fit for bigger panels, because it blows up the presets file. So any preset operation will become  slow and saving presets becomes unreliable.

This is a consequence of using a "bad approach" so we can't fix it. Maybe the PR from AC will work better on large resolution panels.

**Comment by 1liminal1** [comment]
Thank you! 

I have three 64x64 panels and and some HD-WF2 on the way. I'm hoping I can do some pixel mapping working and get one of my prisms going. 

Be interesting to see if it works :)
